// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDboKpuFr4a3NrwV7Ng62s4cMN5YHGdT-8',
    appId: '1:424524528341:web:043fb6de4e502be62c805c',
    messagingSenderId: '424524528341',
    projectId: 'sardor-auth-f3cd4',
    authDomain: 'sardor-auth-f3cd4.firebaseapp.com',
    storageBucket: 'sardor-auth-f3cd4.firebasestorage.app',
    measurementId: 'G-44CG73XJ81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbYU-79JhpAdqAKfO0hsSt9UzAwMXqeg',
    appId: '1:424524528341:android:716874269e0290e22c805c',
    messagingSenderId: '424524528341',
    projectId: 'sardor-auth-f3cd4',
    storageBucket: 'sardor-auth-f3cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlzyp_sJQs4YcqoeWMliCKzxJZ27jSIic',
    appId: '1:424524528341:ios:06cba3641d20abb62c805c',
    messagingSenderId: '424524528341',
    projectId: 'sardor-auth-f3cd4',
    storageBucket: 'sardor-auth-f3cd4.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlzyp_sJQs4YcqoeWMliCKzxJZ27jSIic',
    appId: '1:424524528341:ios:06cba3641d20abb62c805c',
    messagingSenderId: '424524528341',
    projectId: 'sardor-auth-f3cd4',
    storageBucket: 'sardor-auth-f3cd4.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDboKpuFr4a3NrwV7Ng62s4cMN5YHGdT-8',
    appId: '1:424524528341:web:699de989bdc875062c805c',
    messagingSenderId: '424524528341',
    projectId: 'sardor-auth-f3cd4',
    authDomain: 'sardor-auth-f3cd4.firebaseapp.com',
    storageBucket: 'sardor-auth-f3cd4.firebasestorage.app',
    measurementId: 'G-P8TVPB5W53',
  );

}